"""Add bill_id to BillHistory

Revision ID: 0c6f9765c52c
Revises: 7ae4d7de63c4
Create Date: 2024-08-27 23:12:37.169273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6f9765c52c'
down_revision = '7ae4d7de63c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('bill_history_unit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_history_unit_id_fkey', 'unit', ['unit_id'], ['id'])
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
