"""Remove totalUnitUsage and totalBill from Unit model

Revision ID: 3f57bc739964
Revises: c9eb4832238b
Create Date: 2024-08-11 21:57:29.389296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f57bc739964'
down_revision = 'c9eb4832238b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('totalBill')
        batch_op.drop_column('totalUnitUsage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalUnitUsage', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalBill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
