"""add costPerUnit, waterCost and rentCost from Bill model

Revision ID: 7018bbe4a91b
Revises: f96dd3f841a1
Create Date: 2024-08-14 02:26:26.639183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7018bbe4a91b'
down_revision = 'f96dd3f841a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waterCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rentCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('costPerUnit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('costPerUnit')
        batch_op.drop_column('rentCost')
        batch_op.drop_column('waterCost')

    # ### end Alembic commands ###
