"""Add totalUnit and totalBill to Bill model

Revision ID: 71d08867bb5d
Revises: 3f57bc739964
Create Date: 2024-08-12 02:29:36.712613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d08867bb5d'
down_revision = '3f57bc739964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalUnit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('totalBill', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('totalBill')
        batch_op.drop_column('totalUnit')

    # ### end Alembic commands ###
