"""Remove costPerUnit, waterCost, and rentCost from Bill and BillHistory

Revision ID: 7ae4d7de63c4
Revises: dd88cbb7a2c1
Create Date: 2024-08-27 14:33:36.770849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ae4d7de63c4'
down_revision = 'dd88cbb7a2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('rentCost')
        batch_op.drop_column('costPerUnit')
        batch_op.drop_column('waterCost')

    with op.batch_alter_table('bill_history', schema=None) as batch_op:
        batch_op.drop_column('rentCost')
        batch_op.drop_column('costPerUnit')
        batch_op.drop_column('waterCost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waterCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rentCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waterCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rentCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
