"""Update Bill model

Revision ID: c56817643760
Revises: 4197e2173991
Create Date: 2024-09-08 18:35:12.680505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56817643760'
down_revision = '4197e2173991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prevImgUrl', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('prevImgUrl')

    # ### end Alembic commands ###
