"""Remove totalUnitUsage and totalBill from Unit model

Revision ID: c9eb4832238b
Revises: ec1f2f852e3f
Create Date: 2024-08-11 21:55:35.472427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9eb4832238b'
down_revision = 'ec1f2f852e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.drop_column('totalUnitUsage')
        batch_op.drop_column('totalBill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalBill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalUnitUsage', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
