"""empty message

Revision ID: dd88cbb7a2c1
Revises: 25c80b43d0b3
Create Date: 2024-08-27 00:35:42.319115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd88cbb7a2c1'
down_revision = '25c80b43d0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_history')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_sent', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('bill_res_room_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('totalUnit')
        batch_op.drop_column('totalBill')
        batch_op.drop_column('costPerUnit')
        batch_op.drop_column('rentCost')
        batch_op.drop_column('approveStatus')
        batch_op.drop_column('res_room')
        batch_op.drop_column('waterCost')
        batch_op.drop_column('extractionStatus')
        batch_op.drop_column('numberOfUnits')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prevNumberOfUnits', sa.String(), nullable=True))
        batch_op.drop_column('rentCost')
        batch_op.drop_column('waterCost')
        batch_op.drop_column('costPerUnit')

    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_sent', sa.Date(), nullable=True))
        batch_op.drop_constraint('unit_history_res_room_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('status')
        batch_op.drop_column('costPerUnit')
        batch_op.drop_column('rentCost')
        batch_op.drop_column('approveStatus')
        batch_op.drop_column('res_room')
        batch_op.drop_column('waterCost')
        batch_op.drop_column('extractionStatus')
        batch_op.drop_column('numberOfUnits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberOfUnits', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extractionStatus', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('waterCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('res_room', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approveStatus', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rentCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('unit_history_res_room_fkey', 'resident', ['res_room'], ['roomNumber'])
        batch_op.drop_column('date_sent')
        batch_op.drop_column('amount')
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('waterCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rentCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('prevNumberOfUnits')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberOfUnits', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extractionStatus', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('waterCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('res_room', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approveStatus', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rentCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalBill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('totalUnit', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_res_room_fkey', 'resident', ['res_room'], ['roomNumber'])
        batch_op.drop_column('is_sent')
        batch_op.drop_column('date_created')
        batch_op.drop_column('amount')
        batch_op.drop_column('unit_id')

    op.create_table('bill_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numberOfUnits', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('extractionStatus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approveStatus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('res_room', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('costPerUnit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waterCost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rentCost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_month_unit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('previous_month_unit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('previous_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('totalBill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['res_room'], ['resident.roomNumber'], name='bill_history_res_room_fkey'),
    sa.PrimaryKeyConstraint('id', name='bill_history_pkey')
    )
    # ### end Alembic commands ###
