"""Add new fields to Unit model

Revision ID: ec1f2f852e3f
Revises: b6313416166e
Create Date: 2024-08-11 03:18:44.798538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1f2f852e3f'
down_revision = 'b6313416166e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costPerUnit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waterCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rentCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('totalUnitUsage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalBill', sa.Float(), nullable=True))

    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costPerUnit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waterCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rentCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('totalUnitUsage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalBill', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'resident', ['res_room'], ['roomNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('totalBill')
        batch_op.drop_column('totalUnitUsage')
        batch_op.drop_column('rentCost')
        batch_op.drop_column('waterCost')
        batch_op.drop_column('costPerUnit')

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('totalBill')
        batch_op.drop_column('totalUnitUsage')
        batch_op.drop_column('rentCost')
        batch_op.drop_column('waterCost')
        batch_op.drop_column('costPerUnit')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=False)

    # ### end Alembic commands ###
